# Generated by Django 4.2.5 on 2023-09-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="end_date",
            field=models.DateTimeField(null=True, verbose_name="end date"),
        ),
        migrations.AlterField(
            model_name="question",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="date published"
            ),
        ),
    ]
